config:
  credentials:
  - id: https://github.com/PalomoIFCA/private2
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private2:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private2
      repo: https://github.com/PalomoIFCA/private2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private2 git:
        commands:
        - /usr/bin/env sh .sqa/script.ginger_organized_gnu.sh
        container: qc.acc_storm_bright_spren
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cyan_exuberant_eel.sh
        container: qc.doc_kiwi_resilient_goose
      github.com/PalomoIFCA/private2 git:
        commands:
        - /usr/bin/env sh .sqa/script.green_amused_pangolin.sh
        container: qc.doc_fuchsia_practical_unicorn
      github.com/PalomoIFCA/private2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goldenrod_reliable_mongoose.sh
        container: qc.doc_gamboge_fearless_panda
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cadet_respectful_tortoise.sh
        container: qc.lic_snow_zealous_clownfish
  QC.Met:
    repos:
      github.com/PalomoIFCA/private2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.strawberry_polite_dormouse.sh
        container: qc.met_sepia_bewildered_ostrich
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.yellow_clever_parrot.sh
        container: qc.sec_cloud_mysterious_panda
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.amaranth_sweet_caribou.sh
        container: qc.sty_dawn_nurturing_gull
      github.com/PalomoIFCA/private2 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluebell_carefree_fox.sh
        container: qc.sty_saffron_insightful_spider
      github.com/PalomoIFCA/private2 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_analytical_caiman.sh
        container: qc.sty_chili_cautious_okapi
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_trustworthy_wombat.sh
        container: qc.uni_mustard_vigilant_kingfisher
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_peppy_capybara.sh
        container: qc.ver_wine_impulsive_panda
timeout: 5400
