config:
  credentials:
  - id: https://github.com/PalomoIFCA/private2
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private2:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/PalomoIFCA/private2
      repo: https://github.com/PalomoIFCA/private2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private2 git:
        commands:
        - /usr/bin/env sh .sqa/script.storm_reckless_lobster.sh
        container: qc.acc_zinnia_tough_phoenix
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.saffron_creative_opossum.sh
        container: qc.doc_dahlia_focused_hyena
      github.com/PalomoIFCA/private2 git:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_worried_gazelle.sh
        container: qc.doc_burgundy_tough_chipmunk
      github.com/PalomoIFCA/private2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cyan_affectionate_serval.sh
        container: qc.doc_ivory_agile_beaver
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pansy_driven_sloth.sh
        container: qc.lic_purple_productive_opossum
  QC.Met:
    repos:
      github.com/PalomoIFCA/private2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.teal_elated_hamster.sh
        container: qc.met_wave_imaginative_kingfisher
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tangerine_studious_quail.sh
        container: qc.sec_chartreuse_articulate_nymph
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_melancholy_clownfish.sh
        container: qc.sty_gamboge_content_grizzly
      github.com/PalomoIFCA/private2 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.poppy_responsible_turtle.sh
        container: qc.sty_indigo_radiant_owl
      github.com/PalomoIFCA/private2 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.azure_practical_chinchilla.sh
        container: qc.sty_pineapple_hopeful_hare
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private2 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pink_shy_peacock.sh
        container: qc.uni_emerald_goofy_goose
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_perceptive_impala.sh
        container: qc.ver_scarlet_patient_cassowary
timeout: 5400
